# Configuración de conexión para Confluent Cloud
bootstrap.servers=pkc-619z3.us-east1.gcp.confluent.cloud:9092
security.protocol=SASL_SSL
sasl.mechanisms=PLAIN
sasl.username=KF6TTFRA3CDQBQLN
sasl.password=cfltD/pYK/lk7vZquUwMdbcvo4NdLPwCGJkPI/Gp43wUMzLm8lyzZqsg6FFfSCsQ

