
# Credenciales para el Schema Registry
schema.registry.url=https://psrc-1o8pr0d.us-east1.gcp.confluent.cloud
basic.auth.credentials.source=USER_INFO
basic.auth.user.info=4KLM7Y2CR62PLELX:cfltAKu//0cGC8tgccy8yHeP+I/prOtukKxriY8kf5U0i1UcSDKCXlBpeKeGAEtA